### PR TITLE
Add Let's Make Apps

### PR DESCRIPTION
**Pull request by GaegeRoot**
Let's Make Apps is an email digest that aggregates gig listings from a variety of sources and delivers the results to your email inbox every day

### CODE REVIEW

**Comment by andychase** [comment]
See issue #71, I'm not sure about weekly email listings. I'm leaning against including this resource.

Why not just post your sources?? That's the whole spirit behind this resource. Instead you are keeping them a secret and charging for access to them essentially.

**Comment by GaegeRoot** [comment]
@andychase not my resource, actually. But I've found it helpful. 

Also, there's a free option that limits the number of links, so someone can give it a try.

As far as I can tell, many of the results are from various craigslist posts and mentions for developers on twitter. Neither of those things am I interested in manually monitoring constantly.

Additionally, it's daily, not weekly.

**Comment by andychase** [comment]
Yeah I'm just saying that category in general I'm hesitant on.

Scraping Craigslist and Twitter is against their Terms of Service, so this service might be unethical.

I'll continue to think on it. I could add it to the "other" category.

**Comment by GaegeRoot** [comment]
> against their Terms of Service

Interesting point.

**Comment by andychase** [comment]
Added to aggregators list

**Pull request closed without merging**
