### PR TITLE
Add Moonlight

### PR DESCRIPTION
**Pull request by philipithomas**

### CODE REVIEW

**Comment by andychase** [comment]
This looks like another agency but I'll accept it until it's decided what to do with these

**Comment by philipithomas** [comment]
@andychase We're a tech startup building a marketplace - does that still get categorized as an agency?

https://www.startupschool.org/presentations/14

**Comment by andychase** [comment]
@philipithomas 

Are you giving people clients or tasks generally?

I made a new table.. take a look at this new table and let me know where you'd say you fall:

https://github.com/engineerapart/TheRemoteFreelancer/blob/master/README.md#differences-betwteen-types

**Comment by philipithomas** [comment]
@andychase We fall under the `Clients` column - we directly match contractors <> clients. We manage payments and add a processing fee. 

https://www.moonlightwork.com/about/how-it-works

**Comment by andychase** [comment]
One key thing to me is your website says clients "break tasks into subtasks" and "get code sent to you each week".

Just to be 100% clear.. after the client approves a contractor they work with them directly? 

Or does Moonlight do the communication, task break-downs, etc and work with the contractor as sort of a middle man?

**Comment by andychase** [comment]
Oh your link says contractors communicate directly. I moved you guys to clients.

**Pull request merged**
