### PR TITLE
New UK Based Talent Platform 

### PR DESCRIPTION
**Pull request by craig-gigged**
Hi Guys, 

looking to update the list with a new company within the UK. Just launched with clients waiting to post work.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi,

The site seems quite a work-in-progress, to be honest. There doesn't seem to be any work there at the moment, also, there is a lot of "Lorem ipsum dolor sit amet consectetuer" text, especially in the "Help" section. When is this site expected to be launced?

**Comment by craig-gigged** [comment]
Hi, 

Thank you for getting back to me. We have just pushed live a few days ago, I have reached out to our devs as it looks like this section of the site has yet to be published live. Thank you for noticing! Regarding work we currently have a few fairly big clients within the UK ready to use the platform but we are currently trying to get freelancers signed up first.

**Comment by craig-gigged** [comment]
Hi @carlspring, We have matured from my first push and now currently have our first gig that we are looking to fill for a client in London with more i know coming this week. Are you happy for us to make the cut?

**Comment by carlspring** [comment]
@craig-gigged ,

Sure, count me in. My e-mail is my nickname at gmail.com. Feel free to add me on LinkedIn, or Google Hangouts where we can discuss this further.

**Pull request merged**
