### PR TITLE
Add GermanTechJobs and DevITJobs with remote jobs

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by andychase** [comment]
These look like jobs not freelancing gigs. I recommend this repo https://github.com/lukasz-madon/awesome-remote-job

**Comment by Vrq** [comment]
Hey @andychase, on the job boards are both full time and freelance roles (you can use filters to find them)
That's why we added them in the "Jobs" section, next to No Fluff Jobs or Jobhunt.ai which are also not purely freelance gigs :)

So maybe you could reconsider the PR and merge it as well?

**Comment by andychase** [comment]
Oh yeah you are right I forgot there is that jobs section. Let me think on this further!

**Comment by andychase** [comment]
These seem like they are regional so I added them to the [regional](https://github.com/engineerapart/TheRemoteFreelancer/blob/master/README.md#regional-or-language-specific) section

**Pull request closed without merging**
